### PR TITLE
Update dependencies versions in gradle.

### PR DESCRIPTION
**Pull request by IgorGanapolsky**

### CODE REVIEW

**Comment by spengilley** [comment]
Hi there,

Many thanks for updating the gradle files. Could of things. The app gradle file should get it's dependencies from the top level gradle file. This is so that dependencies are only listed once.
Why have some of the preference helper classes been deleted?

**Comment by IgorGanapolsky** [comment]
Ok, I implemented an ext block.  Those preference files were deleted because they were cluttering up the code and not doing anything!  I am in favor of KISS.

**Comment by spengilley** [comment]
Regarding preference files, fair enough!

The app build.gradle now needs to get it's dependencies from the project level build.gradle, as it did originally

**Comment by IgorGanapolsky** [comment]
Why can't app's build.gradle use:
`compileSdkVersion rootProject.compileSdkVersion`?

I don't understand?

**Comment by spengilley** [comment]
It can. I asked that the 3rd party libraries are compiled in the project
build.gradle and referenced in the app build.gradle. What you have done
with the version and sdk stuff is absolutely fine

**Comment by IgorGanapolsky** [comment]
Oh I see.  I believe the industry standard is to compile 3rd party dependencies in the app itself, not top-level gradle file.  Correct me if I'm wrong...

**Comment by spengilley** [comment]
Hi there,

Having the libraries compiled in the top level of a multi module project
means that the same compiles are not duplicated within each module (where
required) and are instead stored in one place and referenced

**Comment by IgorGanapolsky** [comment]
@spengilley Thanks for the nice example.  Have some bitcoin @changetip $1.

**Comment by changetip** [comment]
Hi @spengilley, @IgorGanapolsky sent you a Bitcoin tip worth 4,194 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/734924)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by spengilley** [comment]
Wow dude thanks.  I hope the example is useful for you

**Pull request merged**
